# Heavily aided by: https://gist.github.com/brenns10/f48e1021e8befd2221a2
language: python
python:
  - 3.5
before_install:
 - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
install:
  - pip install sphinx sphinx_rtd_theme
  - pip install pandas
  - pip install git+https://github.com/rmk135/sphinxcontrib-disqus
  - gem install html-proofer
script:
  - make html
  - make doctest
  - htmlproofer _build/html --allow_hash_href --file_ignore "_build/html/search.html"
before_deploy:
  - if [ -n $TRAVIS_TAG -a $TRAVIS_BRANCH = "master" ] ; then ./build_pdf.sh; fi; # If this is tagged, build the latex and the pdf to be released.
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    local-dir: _build/html
    on:
      tags: true
      branch: master
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - _build/AguaClaraTextbook.pdf
      - _build/zipped_latex.zip
    skip_cleanup: true
    on:
      tags: true
      branch: master
