# Heavily aided by: https://gist.github.com/brenns10/f48e1021e8befd2221a2
language: python
python:
  - 3.5
install:
  - pip install sphinx sphinx_rtd_theme
  - gem install html-proofer
script:
  - make html
  - htmlproofer _build/html --allow_hash_href --file_ignore "_build/html/search.html"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: _build/html
