pandoc -V geometry:margin=1in Clarifier.rst -o Clarifier.pdf --pdf-engine=xelatex
pandoc -V geometry:margin=1in ET.rst -o ET.pdf --pdf-engine=xelatex
pandoc -V geometry:margin=1in FlocHH.rst -o FlocHH.pdf --pdf-engine=xelatex
pandoc -V geometry:margin=1in FlocHV.rst -o FlocHV.pdf --pdf-engine=xelatex
pandoc -V geometry:margin=1in FLocVH.rst -o FlocVH.pdf --pdf-engine=xelatex
pandoc -V geometry:margin=1in LFOM.rst -o LFOM.pdf --pdf-engine=xelatex
pandoc -V geometry:margin=1in OStaRS.rst -o OStaRS.pdf --pdf-engine=xelatex
pandoc -V geometry:margin=1in Plant20-80.rst -o Plant20-80.pdf --pdf-engine=xelatex
pandoc -V geometry:margin=1in Doser.rst -o Doser.pdf --pdf-engine=xelatex
