name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
    - name: Install Ruby Dependencies
      run: sudo apt install libcurl4-openssl-dev
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        gem install html-proofer
    - name: Build HTML Docs
      run: |
        make html
        touch _build/html/.nojekyll
    - name: Run HTML Proofer and Doctest
      run: |
        make doctest
        htmlproofer _build/html --allow_hash_href --only_4xx --file_ignore "_build/html/search.html" --url-ignore https://rawgit.com/AguaClara/Textbook/test/html/index.html
    - name: Test Publish Docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: test # The branch the action should deploy to.
        FOLDER: _build/html/ # The folder the action should deploy.
    - name: Test Build LaTeX
      run: make latex
    - name: Test Build PDF
      uses: xu-cheng/latex-action@v2
      with:
        root_file: _build/latex/AguaClaraTextbook.tex
