name: Push to a test branch

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
    - name: Install Ruby Dependencies
      run: sudo apt install libcurl4-openssl-dev
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: dschep/install-pipenv-action@v1
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pip install -r requirements-dev.txt
        gem install html-proofer
    - name: Build HTML Docs
      run: |
        make html
        touch _build/html/.nojekyll
    - name: Run HTML Proofer and Doctest
      run: |
        make doctest
        htmlproofer _build/html --allow_hash_href --only_4xx --file_ignore "_build/html/search.html" --url-ignore https://rawgit.com/AguaClara/Textbook/test/html/index.html
    - name: Push to GH pages.
      run: |
        git checkout gh-pages
        rm -rf branches/${{ github.ref_name }}
        mkdir -p branches/${{ github.ref_name }}
        cp -fR _build/html/* branches/${{ github.ref_name }}
        git add branches/${{ github.ref_name }}/.
        git commit -m "Push update to ${{ github.ref_name }}"
        git push
  #  - name: Test Build LaTeX
  #    run: make latex
   # - name: Test Build PDF
    #  uses: xu-cheng/latex-action@v2
     # with:
      #  working_directory: _build/latex
       # root_file: AguaClaraTextbook.tex
